const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("accountsAPI", {
  list: () => ipcRenderer.invoke("accounts:list"),
  add: () => ipcRenderer.invoke("accounts:add"),
  switchTo: (id) => ipcRenderer.invoke("accounts:switch", id),
  reload: (id) => ipcRenderer.invoke("accounts:reload", id),
  rename: (id, label) => ipcRenderer.invoke("accounts:rename", id, label),
  togglePin: (id) => ipcRenderer.invoke("accounts:togglePin", id),
  toggleMobile: (id) => ipcRenderer.invoke("accounts:toggleMobile", id),
  remove: (id) => ipcRenderer.invoke("accounts:remove", id),
  setLdIndex: (id, ldIndex) => ipcRenderer.invoke("accounts:setLdIndex", id, ldIndex),
  exportCookies: (id) => ipcRenderer.invoke("accounts:exportCookies", id),
  pickCookiesFile: () => ipcRenderer.invoke("accounts:pickCookiesFile"),
  importCookiesText: (id, text) => ipcRenderer.invoke("accounts:importCookiesText", id, text),
  openInEmulator: (id) => ipcRenderer.invoke("accounts:openInEmulator", id),
  quitEmulator: (id) => ipcRenderer.invoke("accounts:quitEmulator", id),
  openAllInEmulators: () => ipcRenderer.invoke("accounts:openAllInEmulators"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  setSettings: (patch) => ipcRenderer.invoke("settings:set", patch),
  openPool: () => ipcRenderer.invoke("pool:openWindow"),
  setBrowserViewVisible: (visible) => ipcRenderer.invoke("browserview:setVisible", visible),
  onActiveChanged: (cb) => ipcRenderer.on("accounts:activeChanged", (_e, id) => cb(id)),
  onAccountsUpdated: (cb) => ipcRenderer.on("accounts:updated", (_e, accts) => cb(accts)),
});
